name: Auto Update Playlists

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Scraper Script
      run: python update_links.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # สั่งเช็กว่ามีไฟล์สร้างขึ้นมาจริงไหม ก่อนที่จะทำการสั่งกดยืนยัน (Commit)
        if [ -f playlist.m3u ] && [ -f playlist.w3u ]; then
          git add playlist.m3u playlist.w3u
          
          if git diff --staged --quiet; then
            echo "ไม่มีการเปลี่ยนแปลงของ Token"
          else
            git commit -m "Auto-updated playlist tokens [skip ci]"
            git push
          fi
        else
          echo "Error: ไม่พบไฟล์เพลย์ลิสต์สำหรับอัปเดต"
          exit 1
        fi
