name: StreamHub Auto App Emulator

on:
  schedule:
    - cron: '0 */6 * * *'  # สั่งให้ระบบตื่นมารันดึงลิงก์ใหม่ทุกๆ 6 ชั่วโมง
  workflow_dispatch:      # เปิดปุ่มให้เรากดรันเองได้แบบ Manual

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Requests library
      run: pip install requests

    - name: Run Emulator Script
      run: python StreamHub.py

    - name: Commit and Push to Repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add StreamHub.w3u
        git diff-index --quiet HEAD || git commit -m "Auto-update all streams to StreamHub.w3u"
        git push
